### ISSUE TITLE
what is the layer "mse_count"?

### ISSUE THREAD

**Issue by hao-zi** [zllljf/SaCNN#1]
There is a new layer "mse_count" in train.prototxt or val.prototxt or trainrcl64.prototxt.
But, my Caffe unknowns the layer.
So, how does the Caffe know the layer "mse_count"?

Thanks.

**Comment by hao-zi** [comment]
I follow readme.txt to compile Caffe.
When I import Caffe in Python, some happen:
```>>> import caffe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chen/hao/tmm/caffe-fcn/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/home/chen/hao/tmm/caffe-fcn/python/caffe/pycaffe.py", line 15, in <module>
    import caffe.io
  File "/home/chen/hao/tmm/caffe-fcn/python/caffe/io.py", line 8, in <module>
    from caffe.proto import caffe_pb2
  File "/home/chen/hao/tmm/caffe-fcn/python/caffe/proto/caffe_pb2.py", line 23, in <module>
    11\n\tbatchsize\x18\x13 \x01(\r\x12\x13\n\x08\x63ropsize\x18\x14 \x01(\r:\x01\x30\x12\x15\n\x06mirror\x18\x15 \x01(\x08:\x05\x66\x61lse\x12\x1f\n\x05\x62lobs\x18\x32 \x03(\x0b\x32\x10.caffe.BlobProto\x12\x10\n\x08\x62lobs_lr\x18\x33 \x03(\x02\x12\x14\n\x0cweight_decay\x18\x34 \x03(\x02\x12\x14\n\trand_skip\x18\x35 \x01(\r:\x01\x30\x12\x1d\n\x10\x64\x65t_fg_threshold\x18\x36 \x01(\x02:\x03\x30.5\x12\x1d\n\x10\x64\x65t_bg_threshold\x18\x37 \x01(\x02:\x03\x30.5\x12\x1d\n\x0f\x64\x65t_fg_fraction\x18\x38 \x01(\x02:\x04\x30.25\x12\x1a\n\x0f\x64\x65t_context_pad\x18: \x01(\r:\x01\x30\x12\x1b\n\rdet_crop_mode\x18; \x01(\t:\x04warp\x12\x12\n\x07new_num\x18< \x01(\x05:\x01\x30\x12\x17\n\x0cnew_channels\x18= \x01(\x05:\x01\x30\x12\x15\n\nnew_height\x18> \x01(\x05:\x01\x30\x12\x14\n\tnew_width\x18? \x01(\x05:\x01\x30\x12\x1d\n\x0eshuffle_images\x18@ \x01(\x08:\x05\x66\x61lse\x12\x15\n\nconcat_dim\x18\x41 \x01(\r:\x01\x31\x12\x36\n\x11hdf5_output_param\x18\xe9\x07 \x01(\x0b\x32\x1a.caffe.HDF5OutputParameter\".\n\nPoolMethod\x12\x07\n\x03MAX\x10\x00\x12\x07\n\x03\x41VE\x10\x01\x12\x0e\n\nSTOCHASTIC\x10\x02\"W\n\x0ePReLUParameter\x12&\n\x06\x66iller\x18\x01 \x01(\x0b\x32\x16.caffe.FillerParameter\x12\x1d\n\x0e\x63hannel_shared\x18\x02 \x01(\x08:\x05\x66\x61lse*\x1c\n\x05Phase\x12\t\n\x05TRAIN\x10\x00\x12\x08\n\x04TEST\x10\x01')
TypeError: __init__() got an unexpected keyword argument 'serialized_options'
```

**Comment by zllljf** [comment]
for the first issue:
mse_count is the count of head in est_dmap, i add the mse_count layer is to calculate and output the MAE and MSE not only in test but also in train.
I suggest you'd best to read the paper first, then understand the network structure, and finally run the code.
for the second issue:
The raw Caffe type i complie is gitted from: https://github.com/BVLC/caffe
not the type of FCN.

**Comment by hao-zi** [comment]
I use the Caffe code from  https://github.com/BVLC/caffe.

**Comment by zllljf** [comment]
You should write PYTHONPATH in .bashrc, and then run source ~/.bashrc.

**Comment by hao-zi** [comment]
yes, i write it.




    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            Hello! Hello
                            
                            
                                
                                    邮箱：haoziyu@gmail.com
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master


On 09/07/2018 14:10, zllljf wrote: You should write PYTHONPATH in .bashrc, and then run source ~/.bashrc.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/zllljf/SaCNN","title":"zllljf/SaCNN","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/zllljf/SaCNN"}},"updates":{"snippets":[{"icon":"PERSON","message":"@zllljf in #1: You should write PYTHONPATH in .bashrc, and then run source ~/.bashrc. \r\n"}],"action":{"name":"View Issue","url":"https://github.com/zllljf/SaCNN/issues/1#issuecomment-419333633"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/zllljf/SaCNN/issues/1#issuecomment-419333633",
"url": "https://github.com/zllljf/SaCNN/issues/1#issuecomment-419333633",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [zllljf/SaCNN] what is the layer \"mse_count\"? (#1)",
"sections": [
{
"text": "",
"activityTitle": "**zllljf**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@zllljf",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"zllljf/SaCNN\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"zllljf/SaCNN\",\n\"issueId\": 1\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/zllljf/SaCNN/issues/1#issuecomment-419333633"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 375916113\n}"
}
],
"themeColor": "26292E"
}
]
