### ISSUE TITLE
mse_count layer failed

### ISSUE THREAD

**Issue by maohule** [zllljf/SaCNN#2]
**Hello! When I run `sh train_sacnn.sh`, the mse_count layer cann't pass.  The program is suspended here and will not continue to execute. What's wrong? Thank you for your help!** 

_I0116 17:04:51.390764 13875 net.cpp:122] Setting up EstdCount_EstdCount_0_split
I0116 17:04:51.390769 13875 net.cpp:129] Top shape: 1 (1)
I0116 17:04:51.390779 13875 net.cpp:129] Top shape: 1 (1)
I0116 17:04:51.390781 13875 net.cpp:137] Memory required for data: 1152092184
I0116 17:04:51.390784 13875 layer_factory.hpp:77] Creating layer loss_map
I0116 17:04:51.390786 13875 net.cpp:84] Creating Layer loss_map
I0116 17:04:51.390789 13875 net.cpp:406] loss_map <- estdmap_p_conv3_0_split_1
I0116 17:04:51.390792 13875 net.cpp:406] loss_map <- densitymap_data_1_split_1
I0116 17:04:51.390796 13875 net.cpp:380] loss_map -> loss_map
I0116 17:04:51.390856 13875 net.cpp:122] Setting up loss_map
I0116 17:04:51.390859 13875 net.cpp:129] Top shape: (1)
I0116 17:04:51.390862 13875 net.cpp:132]     with loss weight 1
I0116 17:04:51.390882 13875 net.cpp:137] Memory required for data: 1152092188
I0116 17:04:51.390884 13875 layer_factory.hpp:77] Creating layer mse_count_

**Comment by harryxz** [comment]
> **Hello! When I run `sh train_sacnn.sh`, the mse_count layer cann't pass. The program is suspended here and will not continue to execute. What's wrong? Thank you for your help!**
> 
> _I0116 17:04:51.390764 13875 net.cpp:122] Setting up EstdCount_EstdCount_0_split I0116 17:04:51.390769 13875 net.cpp:129] Top shape: 1 (1) I0116 17:04:51.390779 13875 net.cpp:129] Top shape: 1 (1) I0116 17:04:51.390781 13875 net.cpp:137] Memory required for data: 1152092184 I0116 17:04:51.390784 13875 layer_factory.hpp:77] Creating layer loss_map I0116 17:04:51.390786 13875 net.cpp:84] Creating Layer loss_map I0116 17:04:51.390789 13875 net.cpp:406] loss_map <- estdmap_p_conv3_0_split_1 I0116 17:04:51.390792 13875 net.cpp:406] loss_map <- densitymap_data_1_split_1 I0116 17:04:51.390796 13875 net.cpp:380] loss_map -> loss_map I0116 17:04:51.390856 13875 net.cpp:122] Setting up loss_map I0116 17:04:51.390859 13875 net.cpp:129] Top shape: (1) I0116 17:04:51.390862 13875 net.cpp:132] with loss weight 1 I0116 17:04:51.390882 13875 net.cpp:137] Memory required for data: 1152092188 I0116 17:04:51.390884 13875 layer_factory.hpp:77] Creating layer mse_count_

Did you finally solve this problem?  How?
I meet a similar problem.
"I0503 17:01:38.917157  3527 layer_factory.hpp:77] Creating layer mse_count
  return f(*args, **kwds)
*** Aborted at 1556874099 (unix time) try "date -d @1556874099" if you are using GNU date ***
PC: @     0x7f5e31a4b273 std::_Hashtable<>::clear()
*** SIGSEGV (@0x9) received by PID 3527 (TID 0x7f5f6c79c740) from PID 9; stack trace: ***
    @     0x7f5f6acb94b0 (unknown)
    @     0x7f5e31a4b273 std::_Hashtable<>::clear()
    @     0x7f5e31a3ab18 google::protobuf::DescriptorPool::FindFileByName()
    @     0x7f5e31a107f8 (unknown)
    @     0x7f5f4ee5d165 PyEval_EvalFrameEx
    @     0x7f5f4eeedcbc (unknown)
    @     0x7f5f4eeedd93 PyEval_EvalCodeEx
    @     0x7f5f4ed75bc5 (unknown)
    @     0x7f5f4ee2a55e PyObject_Call
    @     0x7f5f4ed21085 (unknown)
    @     0x7f5f4ed33f93 (unknown)
    @     0x7f5f4ee2a55e PyObject_Call
    @     0x7f5f4ee5793f PyEval_EvalFrameEx
    @     0x7f5f4eeedcbc (unknown)
    @     0x7f5f4eeedd93 PyEval_EvalCodeEx
    @     0x7f5f4ee559db PyEval_EvalCode
    @     0x7f5f4ee6268d (unknown)
    @     0x7f5f4ed51029 PyCFunction_Call
    @     0x7f5f4ee5e87e PyEval_EvalFrameEx
    @     0x7f5f4eeedcbc (unknown)
    @     0x7f5f4ee5bf49 PyEval_EvalFrameEx
    @     0x7f5f4ee5d649 PyEval_EvalFrameEx
    @     0x7f5f4ee5d649 PyEval_EvalFrameEx
    @     0x7f5f4ee5d649 PyEval_EvalFrameEx
    @     0x7f5f4eeedcbc (unknown)
    @     0x7f5f4eeedd93 PyEval_EvalCodeEx
    @     0x7f5f4ed75ac8 (unknown)
    @     0x7f5f4ee2a55e PyObject_Call
    @     0x7f5f4ee17fef _PyObject_CallMethodIdObjArgs
    @     0x7f5f4ee94964 PyImport_ImportModuleLevelObject
    @     0x7f5f4ee616c8 (unknown)
    @     0x7f5f4ed51049 PyCFunction_Call
"
